---
# Tareas principales del rol cis_reporting

- name: Crear directorio de reportes
  ansible.builtin.file:
    path: "{{ cis_report_output_dir }}"
    state: directory
    mode: '0750'

- name: Generar reporte CIS
  ansible.builtin.template:
    src: cis_report.j2
    dest: "{{ cis_report_output_dir }}/cis_report_{{ inventory_hostname }}.html"
    mode: '0640'
