---
# Handlers para el rol cis_remediation

- name: Reiniciar sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Reiniciar auditd
  ansible.builtin.service:
    name: auditd
    state: restarted
