# =============================================================================
# POC AAP - GCP | Inventario Estatico
# Archivo : inventories/static/hosts.ini
# Nota    : Reemplaza la IP por la IP interna de tu VM en GCE
# =============================================================================

[rhel9_servers]
rhel9-target ansible_host=10.128.0.9 ansible_user=c_alvarenga_c7 ansible_become=true

[rhel9_servers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=~/.ssh/id_rsa