---
oracle_home: "/opt/oracle/product/26ai/dbhomeFree"
oracle_pdb: "FREEPDB1"
oracle_host: "localhost"
oracle_port: "1521"
employee_action: "alta"
employee_role_anterior: ""
employee_oracle_username: ""