---
- name: "Oracle | Crear usuario en FREEPDB1"
  ansible.builtin.shell: |
    {{ oracle_home }}/bin/sqlplus -S {{ oracle_admin_user }}/{{ oracle_admin_password }}@{{ oracle_host }}:{{ oracle_port }}/{{ oracle_pdb }} <<EOF
    CREATE USER {{ employee_username }} IDENTIFIED BY "{{ employee_password }}";
    GRANT CREATE SESSION TO {{ employee_username }};
    EXIT;
    EOF
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "FREE"
    PATH: "{{ oracle_home }}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  register: oracle_create_result
  changed_when: "'User created' in oracle_create_result.stdout"
  failed_when:
    - oracle_create_result.rc != 0
    - "'ORA-01920' not in oracle_create_result.stdout"

- name: "Oracle | Asignar rol al usuario"
  ansible.builtin.shell: |
    {{ oracle_home }}/bin/sqlplus -S {{ oracle_admin_user }}/{{ oracle_admin_password }}@{{ oracle_host }}:{{ oracle_port }}/{{ oracle_pdb }} <<EOF
    GRANT {{ employee_role }} TO {{ employee_username }};
    EXIT;
    EOF
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "FREE"
    PATH: "{{ oracle_home }}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  register: oracle_grant_result
  changed_when: "'Grant succeeded' in oracle_grant_result.stdout"
  failed_when: oracle_grant_result.rc != 0